const level1 = new Level(
    [

        new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new Chicken(),
        // new SmallChicken(),
    ],

    [
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        new SmallChicken(),
    ],

    [
        new Endboss(),
    ],

    [
        new Cloud('img/5_background/layers/4_clouds/1.png', 100),
        new Cloud('img/5_background/layers/4_clouds/2.png', 600),
        new Cloud('img/5_background/layers/4_clouds/1.png', 1100),
        new Cloud('img/5_background/layers/4_clouds/2.png', 1600),
        new Cloud('img/5_background/layers/4_clouds/2.png', 2000),
        new Cloud('img/5_background/layers/4_clouds/1.png', 2600),
        new Cloud('img/5_background/layers/4_clouds/1.png', 3000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 3400),
        new Cloud('img/5_background/layers/4_clouds/1.png', 3800),
        new Cloud('img/5_background/layers/4_clouds/1.png', 4200),
        new Cloud('img/5_background/layers/4_clouds/1.png', 4600),
        new Cloud('img/5_background/layers/4_clouds/1.png', 5000),
        new Cloud('img/5_background/layers/4_clouds/1.png', 5400),
        new Cloud('img/5_background/layers/4_clouds/1.png', 5800),
        new Cloud('img/5_background/layers/4_clouds/2.png', 6200)
    ],

    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 5),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 6),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 7),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 7),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 7),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 7),
    ],

    [
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 400),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 400),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 350)
    ],

    [
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_1.png'),
        new Coin('img/8_coin/coin_2.png')
    ],
);